### ISSUE TITLE
请问文档中这句话是什么意思

### ISSUE THREAD

**Issue by licb-create** [JAVClub/docker#2]
我使用docker部署后，使用web端无法创建种子任务，试了很多次，没办法。 怀疑自己哪里搞错了，这句话的意思是要改什么吗
```
注意2: 由于某些 PT 站点限制默认端口, 故将做种端口改为 51118 及 51118/udp, 请在配置 qBittorrent 自行更改
```

**Comment by licb-create** [comment]
fetcher运行也正常 就是无法下载任何东西 
查看日志都正常 请求能到qBittorrent，目前能创建tag ，但是添加任务啥的不能成功

**Comment by LynMoe** [comment]
需要在 qBittorrent 中将 `用于传入连接的端口` 改为 `51118`

如果可以连接到 qb 的话那可能是 fetcher 拉取部分的配置文件出了点问题, 可以将配置文件的 remote 部分贴上来

**Comment by LynMoe** [comment]
This issue is closed due to not being active. Please feel free to open it again or create a new one and reference this if you have further questions.
