### ISSUE TITLE
主页出来了，但是点击登录无反应

### ISSUE THREAD

**Issue by a532233648** [JAVClub/docker#3]
实在是解决不了了，求助大佬们
看日志是下面的内容，但是我一头雾水
2020/08/04 21:29:08 [error] 7#7: *47 connect() failed (113: Host is unreachable) while connecting to upstream, client: 162.158.165.231, server: ***.com, request: "POST /api/auth/login HTTP/1.1", upstream: "http://172.19.0.4:3000/api/auth/login", host: "***.com", referrer: "https://***.com/"

***.com 是我的域名

**Comment by LynMoe** [comment]
请检查你的 core 容器是否已启动

**Comment by a532233648** [comment]
> 请检查你的 core 容器是否已启动

用docker ps查看是Restarting，但是用docker inspect 显示正在运行，查看容器日志，显示
at Client_MySQL.acquireRawConnection (/usr/app/node_modules/knex/lib/dialects/mysql/index.js:63:12)\n","stream":"stderr","time":"2020-08-05T00:21:59.675634883Z"}
但是mysql正常运行着啊，也按照要求创建了用户及同名数据库，赋予权限等

**Comment by LynMoe** [comment]
请给出 core **详细日志**

**Comment by a532233648** [comment]
> 请给出 core **详细日志**

请问这个详细日志在哪里呢？我直接粘贴上来么？麻烦了
是这个么？

2020/08/05 02:40:22 [error] 8#8: *156 open() "/var/www/default/phpmyadmin2020/index.php" failed (2: No such file or directory), client: 93.115.137.242, server: localhost, request: "GET /phpmyadmin2020/index.php?lang=en HTTP/1.1", host: "140.238.*.*"
2020/08/05 02:40:23 [error] 8#8: *157 open() "/var/www/default/index.php" failed (2: No such file or directory), client: 93.115.137.242, server: localhost, request: "GET /index.php?lang=en HTTP/1.1", host: "140.238.*.*"
2020/08/05 03:50:04 [error] 8#8: *161 open() "/var/www/default/solr/admin/info/system" failed (2: No such file or directory), client: 195.54.160.21, server: localhost, request: "GET /solr/admin/info/system?wt=json HTTP/1.1", host: "140.238.*.*:80"
2020/08/05 04:08:02 [error] 8#8: *168 open() "/var/www/default/index.php" failed (2: No such file or directory), client: 195.54.160.21, server: localhost, request: "GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP HTTP/1.1", host: "140.238.*.*:80"
2020/08/05 04:16:20 [error] 8#8: *169 open() "/var/www/default/adminer-4.2.4.php" failed (2: No such file or directory), client: 195.54.160.67, server: localhost, request: "GET /adminer-4.2.4.php HTTP/1.1", host: "140.238.*.*"
2020/08/05 04:17:57 [error] 8#8: *170 open() "/var/www/default/muieblackcat" failed (2: No such file or directory), client: 173.255.119.42, server: localhost, request: "GET /muieblackcat HTTP/1.1", host: "140.238.*.*"
2020/08/05 04:17:57 [error] 8#8: *171 open() "/var/www/default/phpMyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 173.255.119.42, server: localhost, request: "GET //phpMyAdmin/scripts/setup.php HTTP/1.1", host: "140.238.*.*"
2020/08/05 04:17:57 [error] 8#8: *172 open() "/var/www/default/phpmyadmin/scripts/setup.php" failed (2: No such file or directory), client: 173.255.119.42, server: localhost, request: "GET //phpmyadmin/scripts/setup.php HTTP/1.1", host: "140.238.*.*"
2020/08/05 04:17:57 [error] 8#8: *173 open() "/var/www/default/pma/scripts/setup.php" failed (2: No such file or directory), client: 173.255.119.42, server: localhost, request: "GET //pma/scripts/setup.php HTTP/1.1", host: "140.238.*.*"
2020/08/05 04:17:58 [error] 8#8: *174 open() "/var/www/default/myadmin/scripts/setup.php" failed (2: No such file or directory), client: 173.255.119.42, server: localhost, request: "GET //myadmin/scripts/setup.php HTTP/1.1", host: "140.238.*.*"
2020/08/05 04:17:58 [error] 8#8: *175 open() "/var/www/default/MyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 173.255.119.42, server: localhost, request: "GET //MyAdmin/scripts/setup.php HTTP/1.1", host: "140.238.*.*"
2020/08/05 05:44:15 [error] 8#8: *177 open() "/var/www/default/api/jsonws/invoke" failed (2: No such file or directory), client: 195.54.160.21, server: localhost, request: "POST /api/jsonws/invoke HTTP/1.1", host: "140.238.*.*:80"
2020/08/05 09:47:31 [error] 8#8: *3 open() "/var/www/default/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php" failed (2: No such file or directory), client: 195.54.160.21, server: localhost, request: "GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1", host: "140.238.*.*:80"
